'mode' : 'stream' # ['stream', 'file']
'tracking' : '/home/aidana/PycharmProjects/vat-capture/data-tracking/GAX/L2 - left.txt'# file to stream from
'defaults' : 'geometry-default.yaml'
'refresh_timeout' : 30 # in milliseconds
'stats_timeout' : 100 # in milliseconds
'time_filter' : 500 # in milliseconds
'markers': # must be within the data-geometry folder
  '300': # has to correspond to the id in the .ini file
    'geom' : 'sacrum_marker.ini'
  '4':
    'geom' : 'drillnew.ini'
'geometries': # for meshes, must be in the data-stl folder
  'drill':
    'marker': 4
    'type': 'mesh'
    'data': 'direction drillsleeve.stl'
    'color': [ 0,255,255,0.2 ]
    'vis': true
  'drillsleeve-dir':
    'marker' : 4
    'type' : 'line'
    'data' : [134.358, -0.123, 73.332, 250.982, 0.420, 72.709]
    'color' : [0, 0, 0, 0]
  'drillsleeve-tip':
    'marker' : 4
    'type' : 'point'
    'data' : [-146.056, 0.591, 67.520]
    'color' : [0, 0, 0, 0]
  'drillsleeve-origin':
    'marker' : 4
    'type' : 'point'
    'data' : [134.358, -0.123, 73.332]
    'color' : [0, 0, 0, 0]
'statistics':
  'distance to entry 2D':
    'type' : 'distance_2d'
    'args' : ['entry', 'drillsleeve-tip']
    'column' : 0
  'distance to entry 3D':
    'type' : 'distance_3d'
    'args' : ['entry', 'drillsleeve-tip']
    'column' : 1
  'angle to trajectory':
    'type' : 'angle_points_to_trajectory'
    'args' : ['traj', 'drillsleeve-origin', 'drillsleeve-tip']
    'column' : 2
