'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L1.stl'
  'entry':
    'type' : 'point'
    'data' : [11.665, 131.163, -224.008]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [29.761, 110.061, -257.516,11.665, 131.163, -224.008, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L1.stl'
  'entry':
    'type' : 'point'
    'data' : [65.683, 136.363, -222.115]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-288.482, 210.273, 14.056]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-288.482, 210.273, 14.056]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [53.429, 112.417, -256.653, 65.683, 136.363, -222.115,150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L2.stl'
  'entry':
    'type' : 'point'
    'data' : [21.093, 100.933, -206.993]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-250.749, 210.868, 2.760]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-250.749, 210.868, 2.760]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [31.166, 77.484, -246.293,21.093, 100.933, -206.993, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L2.stl'
  'entry':
    'type' : 'point'
    'data' : [53.424, 103.068, -210.021]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-251.117, 209.437, 15.575]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-251.117, 209.437, 15.575]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [50.851, 80.006, -245.901,53.424, 103.068, -210.021, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L3.stl'
  'entry':
    'type' : 'point'
    'data' : [8.448, 69.484, -193.685]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-213.573, 208.917, 3.960]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-213.573, 208.917, 3.960]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [37.519, 44.594, -227.514,8.448, 69.484, -193.685, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L3.stl'
  'entry':
    'type' : 'point'
    'data' : [73.820, 72.940, -188.587]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-213.957, 207.422, 17.346]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-213.957, 207.422, 17.346]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [50.477, 44.900, -226.900,73.820, 72.940, -188.587, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L4.stl'
  'entry':
    'type' : 'point'
    'data' : [7.978, 36.309, -174.661]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-173.957, 206.139, 4.333]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-173.957, 206.139, 4.333]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [33.402, 11.098, -203.843,7.978, 36.309, -174.661, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L4.stl'
  'entry':
    'type' : 'point'
    'data' : [77.544, 36.279, -172.615]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-174.353, 204.599, 18.117]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-174.353, 204.599, 18.117]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [47.399, 10.262, -203.565,77.544, 36.279, -172.615, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L5.stl'
  'entry':
    'type' : 'point'
    'data' : [7.689, 16.519, -150.758]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-135.549, 203.897, 6.128]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-135.549, 203.897, 6.128]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [17.538, -7.815, -151.361,7.689, 16.519, -150.758, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/L5.stl'
  'entry':
    'type' : 'point'
    'data' : [57.066, 13.885, -153.128]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-135.966, 202.012, 20.500]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-135.966, 202.012, 20.500]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [45.805, -20.147, -173.046,57.066, 13.885, -153.128, 150]
    'color' : [0.,1.0,0.,1]
'T12 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T12.stl'
  'entry':
    'type' : 'point'
    'data' : [25.080, 163.075, -238.800]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-100.163, 200.862, 6.498]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-100.163, 200.862, 6.498]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [29.341, 143.865, -273.454, 25.080, 163.075, -238.800,150]
    'color' : [0.,1.0,0.,1]
'T12 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T12.stl'
  'entry':
    'type' : 'point'
    'data' : [48.130, 164.900, -238.591]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-100.604, 198.945, 21.722]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-100.604, 198.945, 21.722]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [50.962, 146.040, -272.494,48.130, 164.900, -238.591, 150]
    'color' : [0.,1.0,0.,1]
'T11 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T11.stl'
  'entry':
    'type' : 'point'
    'data' : [15.720, 195.044, -248.711]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [26.514, 171.242, -288.899, 15.720, 195.044, -248.711, 150]
    'color' : [0.,1.0,0.,1]
'T11 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T11.stl'
  'entry':
    'type' : 'point'
    'data' : [44.027, 193.546, -254.276]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-361.783, 213.947, 10.161]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-361.783, 213.947, 10.161]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [46.051, 172.797, -288.670, 44.027, 193.546, -254.276, 150]
    'color' : [0.,1.0,0.,1]
'T10 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T10.stl'
  'entry':
    'type' : 'point'
    'data' : [15.101, 221.173, -266.151]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-324.418, 213.243, 0.623]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-324.418, 213.243, 0.623]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [26.319, 195.484, -306.012, 15.101, 221.173, -266.151, 150]
    'color' : [0.,1.0,0.,1]
'T10 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T10.stl'
  'entry':
    'type' : 'point'
    'data' : [42.050, 220.582, -269.782]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-324.760, 212.164, 12.394]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-324.760, 212.164, 12.394]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [43.717, 196.818, -305.764,42.050, 220.582, -269.782, 150]
    'color' : [0.,1.0,0.,1]
'T9 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T9.stl'
  'entry':
    'type' : 'point'
    'data' : [14.692, 246.527, -284.424]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-324.418, 213.243, 0.623]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-324.418, 213.243, 0.623]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [25.245, 218.157, -316.794,14.692, 246.527, -284.424, 150]
    'color' : [0.,1.0,0.,1]
'T9 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T9.stl'
  'entry':
    'type' : 'point'
    'data' : [39.712, 245.340, -285.984]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-324.760, 212.164, 12.394]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-324.760, 212.164, 12.394]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [41.741, 219.471, -316.554,39.712, 245.340, -285.984, 150]
    'color' : [0.,1.0,0.,1]
'T8 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T8.stl'
  'entry':
    'type' : 'point'
    'data' : [13.637, 269.144, -303.124]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [24.938, 235.030, -334.700, 13.637, 269.144, -303.124, 150]
    'color' : [0.,1.0,0.,1]
'T8 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T8.stl'
  'entry':
    'type' : 'point'
    'data' : [39.750, 267.129, -304.346]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [40.946, 236.145, -334.343,39.750, 267.129, -304.346, 150]
    'color' : [0.,1.0,0.,1]
'T7 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T7.stl'
  'entry':
    'type' : 'point'
    'data' : [16.345, 286.579, -323.823]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [26.773, 253.729, -350.010,16.345, 286.579, -323.823, 150]
    'color' : [0.,1.0,0.,1]
'T7 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T7.stl'
  'entry':
    'type' : 'point'
    'data' : [41.417, 287.532, -326.618]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [35.169, 253.991, -350.038,41.417, 287.532, -326.618, 150]
    'color' : [0.,1.0,0.,1]
'T6 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T6.stl'
  'entry':
    'type' : 'point'
    'data' : [15.331, 301.932, -346.608]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [26.185, 268.321, -367.532, 15.331, 301.932, -346.608, 150]
    'color' : [0.,1.0,0.,1]
'T6 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T6.stl'
  'entry':
    'type' : 'point'
    'data' : [41.327, 303.270, -347.556]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [34.474, 268.707, -367.737,41.327, 303.270, -347.556, 150]
    'color' : [0.,1.0,0.,1]
'T5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T5.stl'
  'entry':
    'type' : 'point'
    'data' : [10.570, 314.972, -372.992]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [23.496, 277.100, -386.389, 10.570, 314.972, -372.992, 150]
    'color' : [0.,1.0,0.,1]
'T5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T5.stl'
  'entry':
    'type' : 'point'
    'data' : [39.241, 314.584, -373.568]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [31.780, 277.343, -386.851,39.241, 314.584, -373.568, 150]
    'color' : [0.,1.0,0.,1]
'T4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T4.stl'
  'entry':
    'type' : 'point'
    'data' : [14.156, 321.826, -397.494]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [19.545, 286.063, -407.552, 14.156, 321.826, -397.494, 150]
    'color' : [0.,1.0,0.,1]
'T4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T4.stl'
  'entry':
    'type' : 'point'
    'data' : [36.225, 321.429, -400.871]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [27.130, 285.946, -408.037,36.225, 321.429, -400.871, 150]
    'color' : [0.,1.0,0.,1]
'T3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T3.stl'
  'entry':
    'type' : 'point'
    'data' : [20.118, 280.523, -408.670]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [28.061, 248.897, -408.352, 20.118, 280.523, -408.670, 150]
    'color' : [0.,1.0,0.,1]
'T3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S220525/T3.stl'
  'entry':
    'type' : 'point'
    'data' : [47.103, 275.992, -405.678]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : []
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [35.196, 247.767, -408.216,47.103, 275.992, -405.678, 150]
    'color' : [0.,1.0,0.,1]









