'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L1 (GC 3 SD 1.5) .stl'
  'entry':
    'type' : 'point'
    'data' : [-287.399, -47.622, -55.805]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-307.424, -15.291, -7.090]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-307.424, -15.291, -7.090]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-287.399, -47.622, -55.805, -307.424, -15.291, -7.090, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L1 (GC 3 SD 1.5) .stl'
  'entry':
    'type' : 'point'
    'data' : [-285.157, -60.313, 41.561]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-308.136, -15.240, 6.066]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-308.136, -15.240, 6.066]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-285.157, -60.313, 41.561, -308.136, -15.240, 6.066, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L2 (GC 3 SD 1.5) .stl'
  'entry':
    'type' : 'point'
    'data' : [-253.781, -31.809, -53.664]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-274.463, 1.005, -5.550]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-274.463, 1.005, -5.550]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-253.781, -31.809, -53.664, -274.463, 1.005, -5.550, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L2 (GC 3 SD 1.5) .stl'
  'entry':
    'type' : 'point'
    'data' : [-250.387, -43.833, 42.457]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-275.096, 1.214, 8.1091]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-275.096, 1.214, 8.109]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-250.387, -43.833, 42.457,-275.096, 1.214, 8.109, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-213.489, -26.011, -36.291]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-241.270, 18.313, -3.379]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-241.270, 18.313, -3.379]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-213.489, -26.011, -36.291,-241.270, 18.313, -3.379, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-211.377, -34.885, 16.472]
    'color' : []
  'mid':
    'type' : 'point'
    'data' : [-242.143, 18.399, 10.669]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-242.143, 18.399, 10.669]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-211.377, -34.885, 16.472, -242.143, 18.399, 10.669, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-174.562, -15.282, -6.916]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-207.023, 36.997, -1.200]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-207.023, 36.997, -1.200]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-174.562, -15.282, -6.916,-207.023, 36.997, -1.200, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-191.415, 6.595, 64.452]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-207.660, 36.966, 13.137]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-207.660, 36.966, 13.137]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-191.415, 6.595, 64.452,-207.660, 36.966, 13.137, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L5 (GC 3 SD 1.5) .stl'
  'entry':
    'type' : 'point'
    'data' : [-155.022, 30.587, -52.348]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-173.944, 56.532, 0.457]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-173.944, 56.532, 0.457]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-155.022, 30.587, -52.348,-173.944, 56.532, 0.457, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L5 (GC 3 SD 1.5) .stl'
  'entry':
    'type' : 'point'
    'data' : [-148.114, 10.022, 46.782]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-174.611, 56.158, 15.337]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-174.611, 56.158, 15.337]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-148.114, 10.022, 46.782,-174.611, 56.158, 15.337, 150]
    'color' : [0.,1.0,0.,1]
'L6 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L6 (GC 3 SD 1.5) .stl'
  'entry':
    'type' : 'point'
    'data' : [-117.687, 35.134, -37.115]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-145.799, 74.365, 1.487]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-145.799, 74.365, 1.487]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-117.687, 35.134, -37.115,-145.799, 74.365, 1.487, 150]
    'color' : [0.,1.0,0.,1]
'L6 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/L6 (GC 3 SD 1.5) .stl'
  'entry':
    'type' : 'point'
    'data' : [-112.517, 23.944, 28.068]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-146.514, 74.512, 17.745]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-146.514, 74.512, 17.745]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-112.517, 23.944, 28.068,-146.514, 74.512, 17.745, 150]
    'color' : [0.,1.0,0.,1]
'T13 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/T13 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-385.425, -93.139, -59.904]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-401.847, -60.088, -10.332]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-401.847, -60.088, -10.332]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-385.425, -93.139, -59.904,-401.847, -60.088, -10.332, 150]
    'color' : [0.,1.0,0.,1]
'T13 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/T13 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-383.583, -109.028, 33.514]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-321.714, 217.187, 32.582]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-402.408, -60.137, 0.730]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-383.583, -109.028, 33.514,-402.408, -60.137, 0.730, 150]
    'color' : [0.,1.0,0.,1]
'T14 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/T14 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-345.540, -93.121, -40.677]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-371.243, -46.515, -9.265]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-371.243, -46.515, -9.265]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-345.540, -93.121, -40.677,-371.243, -46.515, -9.265, 150]
    'color' : [0.,1.0,0.,1]
'T14 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/T14 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-344.034, -101.179, 10.121]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-371.856, -46.534, 2.420]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-371.856, -46.534, 2.420]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-344.034, -101.179, 10.121,-371.856, -46.534, 2.420, 150]
    'color' : [0.,1.0,0.,1]
'T15 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/T15 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-311.035, -86.400, -10.457]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-339.421, -31.575, -7.639]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-339.421, -31.575, -7.639]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-311.035, -86.400, -10.457,-339.421, -31.575, -7.639, 150]
    'color' : [0.,1.0,0.,1]
'T15 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 3-stls/marker1/T15 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-320.902, -70.654, 48.755]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-339.814, -31.593, 4.755]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-339.814, -31.593, 4.755]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-320.902, -70.654, 48.755,-339.814, -31.593, 4.755, 150]
    'color' : [0.,1.0,0.,1]