'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [129.992, -173.642, 12.819]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-285.066, 215.974, 21.851]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-285.066, 215.974, 21.851]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [132.228,-164.090,-14.282, 128.743,-178.978,27.957, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [155.298, -150.601, 44.619]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-285.469, 214.828, 34.367]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-285.469, 214.828, 34.367]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [173.122, -126.017, 33.207, 148.092, -160.541, 49.233, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [106.248, -148.467, 20.527]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-247.708, 214.682, 23.151]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-247.708, 214.682, 23.151]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [110.517,-133.2,-5.104, 104.07, -156.255, 33.6, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [128.890, -130.925, 52.525]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-248.122, 213.506, 35.991]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-248.122, 213.506, 35.991]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [144.712,-104.584,36.333,123.322,-140.194,58.223, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [73.629, -131.003, 28.980]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-210.565, 212.241, 24.478]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-210.565, 212.241, 24.478]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [71.987, -121.986, 0.831,74.510, -135.848, 44.105, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [93.366, -114.857, 54.939]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-210.998, 211.012, 37.890]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-210.998, 211.012, 37.890]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [103.698, -91.196, 29.562, 90.296, -121.885, 62.476, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [42.845, -110.990, 39.504]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-170.992, 208.924, 25.000]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-170.992, 208.924, 25.000]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [42.771, -100.687, 11.945, 42.885, -116.624, 54.573, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [66.619, -94.408, 66.964]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-171.438, 207.658, 38.810]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-171.438, 207.658, 38.810]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [79.846, -72.077, 44.301, 61.821, -102.508, 75.185,150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [6.304, -91.161, 46.779]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-132.623, 206.187, 26.930]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-132.623, 206.187, 26.930]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-4.644, -82.979, 25.642, 15.151, -97.771, 63.858, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [51.133, -65.441, 87.162]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-133.096, 204.588, 41.334]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-133.096, 204.588, 41.334]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [71.270,-45.622,76.792,39.854,-76.542,92.971, 150]
    'color' : [0.,1.0,0.,1]
'T11 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [206.919, -193.172, 32.564]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-392.410, 224.020, 17.862]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-392.410, 224.020, 17.862]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [221.904, -173.123, 16.465, 198.440, -204.517, 41.674, 150]
    'color' : [0.,1.0,0.,1]
'T11 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [187.279, -211.138, 11.038]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-392.763, 223.446, 28.992]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-392.763, 223.446, 28.992]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [199.645, -193.250, -15.124, 181.997, -218.779, 22.213, 150]
    'color' : [0.,1.0,0.,1]
'T12 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [166.632, -190.621, 18.335]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-358.348, 220.015, 18.997]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-358.348, 220.015, 18.997]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [180.501, -170.526, -8.053, 163.133, -195.690, 24.992, 150]
    'color' : [0.,1.0,0.,1]
'T12 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'C211013-stls-marke1/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [182.466, -174.007, 30.577]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-358.704, 219.438, 30.227]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-358.704, 219.438, 30.227]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [194.529, -156.893, 9.689, 175.763, -183.514, 42.182, 150]
    'color' : [0.,1.0,0.,1]
