'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [83.954, -164.340, 17.396]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-285.066, 215.974, 21.851]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-285.066, 215.974, 21.851]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [84.562, -147.661, -5.492, 83.637, -173.057, 29.358, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [115.096, -143.779, 50.201]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-285.469, 214.828, 34.367]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-285.469, 214.828, 34.367]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [125.114, -120.529, 39.320, 110.152, -155.254, 55.570, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [63.686, -143.768, 33.751]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-247.708, 214.682, 23.151]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-247.708, 214.682, 23.151]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [64.528, -124.905, 8.591, 63.309, -152.195, 44.990, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [93.968, -126.148, 65.817]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-248.122, 213.506, 35.991]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-248.122, 213.506, 35.991]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [106.623, -98.494, 50.937,89.072, -136.845, 71.573,150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [38.377, -128.122, 41.601]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-210.565, 212.241, 24.478]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-210.565, 212.241, 24.478]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [35.897, -121.947, 16.859,40.302, -132.916, 60.806,150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [64.692, -108.714, 67.627]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-210.998, 211.012, 37.890]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-210.998, 211.012, 37.890]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [76.169, -86.503, 49.157, 58.832, -120.055, 77.057,150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [11.347, -107.943, 54.777]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-170.992, 208.924, 25.000]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-170.992, 208.924, 25.000]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [12.393, -97.427, 27.206, 10.781, -113.636, 69.701,150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [39.990, -90.253, 79.722]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-171.438, 207.658, 38.810]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-171.438, 207.658, 38.810]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [50.569, -70.530, 51.862, 36.669, -96.444, 88.468,150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-19.893, -92.343, 58.694]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-132.623, 206.187, 26.930]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-132.623, 206.187, 26.930]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-31.205, -85.996, 34.309, -12.567, -96.454, 74.488, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [31.323, -62.469, 102.773]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-133.096, 204.588, 41.334]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-133.096, 204.588, 41.334]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [54.833, -43.654, 90.362, 20.939, -70.779, 108.255, 150]
    'color' : [0.,1.0,0.,1]
'T11 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [140.308, -192.912, -4.114]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-358.348, 220.015, 18.997]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-358.348, 220.015, 18.997]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [147.909, -176.278, -25.656, 135.915, -202.527, 8.336, 150]
    'color' : [0.,1.0,0.,1]
'T11 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [166.022, -169.225, 17.850]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-358.704, 219.438, 30.227]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-358.704, 219.438, 30.227]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [172.141, -155.381, 6.701, 158.151, -187.030, 32.189, 150]
    'color' : [0.,1.0,0.,1]
'T12 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [118.740, -178.366, 13.607]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-321.332, 218.033, 20.794]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-321.332, 218.033, 20.794]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [126.159, -156.860, -11.344,116.620, -184.511, 20.736, 150]
    'color' : [0.,1.0,0.,1]
'T12 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'GAX-stls-marker1/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [138.791, -157.828, 29.328]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-321.714, 217.187, 32.582]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-321.714, 217.187, 32.582]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [145.255, -138.793, 13.037,134.083, -171.691, 41.192, 150]
    'color' : [0.,1.0,0.,1]
