'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-288.864, 86.979, -29.057]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-286.852, 125.975, -5.303]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-286.852, 125.975, -5.303]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-286.852, 125.975, -5.303,-288.864, 86.979, -29.057, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-289.640, 79.304, 18.995]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-286.988, 125.685, 4.467]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-286.988, 125.685, 4.467]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-286.988, 125.685, 4.467,-289.640, 79.304, 18.995, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-253.781, 84.505, -21.319]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-255.639, 125.889, -6.685]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-255.639, 125.889, -6.685]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-255.639, 125.889, -6.685,-253.781, 84.505, -21.319, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-254.010, 80.016, 7.132]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-255.728, 124.155, 12.186]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-255.728, 124.155, 12.186]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-255.728, 124.155, 12.186,-254.010, 80.016, 7.132, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-221.381, 83.713, -11.598]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-224.362, 128.007, -5.653]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-224.362, 128.007, -5.653]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-218.911, 29.336, -24.880,-230.528,140.933,-6.218,150] #[-224.362, 128.007, -5.653,-221.381, 83.713, -11.598, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-223.712, 82.834, 27.161]
    'color' :  [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-224.896, 127.801, 4.531]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-224.896, 127.801, 4.531]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-224.896, 127.801, 4.531,-223.712, 82.834, 27.161, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-188.201, 90.724, -31.082]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-193.403, 132.592, -3.109]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-193.403, 132.592, -3.109]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-193.403, 132.592, -3.109,-188.201, 90.724, -31.082, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-188.456, 76.137, 24.060]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-193.643, 132.025, 7.648]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-193.643, 132.025, 7.648]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-193.643, 132.025, 7.648,-188.456, 76.137, 24.060, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-160.033, 94.830, -25.636]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-160.915, 136.713, -1.612]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-160.915, 136.713, -1.612]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-160.915, 136.713, -1.612,-160.033, 94.830, -25.636, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-160.579, 89.127, 13.852]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-161.020, 135.856, 11.235]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-161.020, 135.856, 11.235]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-161.020, 135.856, 11.235,-160.579, 89.127, 13.852, 150]
    'color' : [0.,1.0,0.,1]
'T9 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/T9 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-392.410, 224.020, 17.862]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-392.410, 224.020, 17.862]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-392.410, 224.020, 17.862,-392.410, 224.020, 17.862, 150]
    'color' : [0.,1.0,0.,1]
'T9 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/T9 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-392.763, 223.446, 28.992]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-392.763, 223.446, 28.992]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-392.763, 223.446, 28.992,-392.763, 223.446, 28.992,  150]
    'color' : [0.,1.0,0.,1]
'T10 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-378.900, 82.838, -31.208]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-374.169, 132.458, -11.924]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-374.169, 132.458, -11.924]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-374.169, 132.458, -11.924,-378.900, 82.838, -31.208,  150]
    'color' : [0.,1.0,0.,1]
'T10 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-378.698, 90.478, 9.190]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-374.347, 132.459, 2.651]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-374.347, 132.459, 2.651]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-374.347, 132.459, 2.651,-378.698, 90.478, 9.190,  150]
    'color' : [0.,1.0,0.,1]
'T11 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-350.602, 89.320, -22.730]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-347.128, 129.866, -8.116]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-347.128, 129.866, -8.116]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-347.128, 129.866, -8.116,-350.602, 89.320, -22.730,  150]
    'color' : [0.,1.0,0.,1]
'T11 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-350.393, 93.157, 4.447]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-347.207, 129.236, 4.668]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-347.207, 129.236, 4.668]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-347.207, 129.236, 4.668,-350.393, 93.157, 4.447,  150]
    'color' : [0.,1.0,0.,1]
'T12 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-321.339, 89.816, -12.286]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-318.132, 124.423, -13.371]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-318.132, 124.423, -13.371]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-318.132, 124.423, -13.371,-321.332, 218.033, 20.794, 150]
    'color' : [0.,1.0,0.,1]
'T12 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'I210050-stls/marker1/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-321.830, 96.565, 17.469]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-319.308, 123.795, 8.739]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-319.308, 123.795, 8.739]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-319.308, 123.795, 8.739,-321.830, 96.565, 17.469, 150]
    'color' : [0.,1.0,0.,1]
