'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L1.stl'
  'entry':
    'type' : 'point'
    'data' : [-339.441, 83.091, -34.875]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-340.370, 87.526, -31.250]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-345.246, 110.816, -12.215]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-345.246, 110.816, -12.215, -340.370, 87.526, -31.250, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L1.stl'
  'entry':
    'type' : 'point'
    'data' : [-340.986, 77.168, -4.014]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-341.919, 83.367, -6.271]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-344.027, 97.375, -11.372]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-344.027, 97.375, -11.372, -341.919, 83.367, -6.271, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L2.stl'
  'entry':
    'type' : 'point'
    'data' : [-309.354, 82.892, -32.191]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-310.377, 88.923, -6.743]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-312.538, 103.284, -11.974]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-312.538, 103.284, -11.974, -310.377, 88.923, -6.743, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L2.stl'
  'entry':
    'type' : 'point'
    'data' : [-340.986, 77.168, -4.014]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-341.919, 83.367, -6.271]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-345.246, 110.816, -12.215]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-345.246, 110.816, -12.215, -341.919, 83.367, -6.271, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L3.stl'
  'entry':
    'type' : 'point'
    'data' : [-277.197, 92.143, -34.570]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-278.224, 97.434, -30.578]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-282.889, 121.470, -12.437]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-282.889, 121.470, -12.437, --278.224, 97.434, -30.578, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L3.stl'
  'entry':
    'type' : 'point'
    'data' : [-279.941, 82.460, -4.999]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-281.605, 92.483, -6.791]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-284.034, 107.110, -9.406]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-284.034, 107.110, -9.406,-281.605, 92.483, -6.791, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L4.stl'
  'entry':
    'type' : 'point'
    'data' : [-248.510, 94.656, -34.147]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-250.052, 101.762, -28.809]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-255.261, 125.767, -10.777]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-255.261, 125.767, -10.777, -250.052, 101.762, -28.809, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L4.stl'
  'entry':
    'type' : 'point'
    'data' : [-245.984, 94.458, 1.283]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-247.175, 100.639, -2.254]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-255.261, 125.767, -10.777]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-255.261, 125.767, -10.777, -247.175, 100.639, -2.254, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L5.stl'
  'entry':
    'type' : 'point'
    'data' : [-217.927, 105.978, -39.141]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-218.175, 110.991, -33.415]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-219.171, 131.051, -10.499]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-219.171, 131.051, -10.499, -218.175, 110.991, -33.415, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'misspiggy3/L5.stl'
  'entry':
    'type' : 'point'
    'data' : [-219.722, 96.967, -3.397]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-220.639, 104.476, -6.082]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-222.358, 118.561, -11.118]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-222.358, 118.561, -11.118,-220.639, 104.476, -6.082, 150]
    'color' : [0.,1.0,0.,1]