'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/union.stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-243.964, 259.024, -2.308]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-243.964, 259.024, -2.308]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-243.964, 259.024, -2.308, -243.964, 259.024, -2.308, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-244.593, 257.984, 10.234]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-244.593, 257.984, 10.234]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-244.593, 257.984, 10.234,-244.593, 257.984, 10.234, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-206.576, 249.236, -1.128]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-206.576, 249.236, -1.128]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-206.576, 249.236, -1.128,-206.576, 249.236, -1.128, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-207.236, 248.118, 11.833]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-207.236, 248.118, 11.833]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-207.236, 248.118, 11.833,-207.236, 248.118, 11.833, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-170.114, 238.431, -0.140]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-170.114, 238.431, -0.140]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-170.114, 238.431, -0.140,-170.114, 238.431, -0.140, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : []
  'mid':
    'type' : 'point'
    'data' : [-170.874, 237.381, 13.323]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-170.874, 237.381, 13.323]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-170.874, 237.381, 13.323,-170.874, 237.381, 13.323, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-133.280, 226.731, 0.593]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-133.280, 226.731, 0.593]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-133.280, 226.731, 0.593, -133.280, 226.731, 0.593, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-133.951, 225.624, 14.433]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-133.951, 225.624, 14.433]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-133.951, 225.624, 14.433,-133.951, 225.624, 14.433, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-95.587, 215.758, 2.465]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-132.623, 206.187, 26.930]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-95.587, 215.758, 2.465,-95.587, 215.758, 2.465, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-96.352, 214.328, 16.950]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-96.352, 214.328, 16.950]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-96.352, 214.328, 16.950,-96.352, 214.328, 16.950, 150]
    'color' : [0.,1.0,0.,1]
'L6 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L6 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-61.377, 205.306, 2.346]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-61.377, 205.306, 2.346]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-61.377, 205.306, 2.346,-61.377, 205.306, 2.346, 150]
    'color' : [0.,1.0,0.,1]
'L6 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/L6 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-62.130, 204.053, 17.702]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-62.130, 204.053, 17.702]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-62.130, 204.053, 17.702, -62.130, 204.053, 17.702, 150]
    'color' : [0.,1.0,0.,1]
'T10 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-392.410, 224.020, 17.862]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-392.410, 224.020, 17.862]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-392.410, 224.020, 17.862, -392.410, 224.020, 17.862, 150]
    'color' : [0.,1.0,0.,1]
'T10 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-392.763, 223.446, 28.992]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-392.763, 223.446, 28.992]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-392.763, 223.446, 28.992, -392.763, 223.446, 28.992, 150]
    'color' : [0.,1.0,0.,1]
'T11 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-314.614, 278.170, -5.207]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-314.614, 278.170, -5.207]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-314.614, 278.170, -5.207,-314.614, 278.170, -5.207, 150]
    'color' : [0.,1.0,0.,1]
'T11 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-315.064, 277.690, 6.074]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-315.064, 277.690, 6.074]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-315.064, 277.690, 6.074,-315.064, 277.690, 6.074, 150]
    'color' : [0.,1.0,0.,1]
'T12 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-280.190, 269.718, -3.550]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-280.190, 269.718, -3.550]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-280.190, 269.718, -3.550,-280.190, 269.718, -3.550, 150]
    'color' : [0.,1.0,0.,1]
'T12 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 2/left marker/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-280.717, 269.004, 8.266]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-280.717, 269.004, 8.266]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-280.717, 269.004, 8.266,-280.717, 269.004, 8.266, 150]
    'color' : [0.,1.0,0.,1]