'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/Marker 1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-285.066, 215.974, 21.851]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-285.066, 215.974, 21.851]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-285.066, 215.974, 21.851, -285.066, 215.974, 21.851, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/Marker 2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-285.469, 214.828, 34.367]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-285.469, 214.828, 34.367]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-285.469, 214.828, 34.367, -285.469, 214.828, 34.367, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-247.708, 214.682, 23.151]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-247.708, 214.682, 23.151]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-247.708, 214.682, 23.151, -247.708, 214.682, 23.151, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-248.122, 213.506, 35.991]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-248.122, 213.506, 35.991]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-248.122, 213.506, 35.991,-248.122, 213.506, 35.991, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-210.565, 212.241, 24.478]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-210.565, 212.241, 24.478]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-210.565, 212.241, 24.478,-210.565, 212.241, 24.478, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : []
  'mid':
    'type' : 'point'
    'data' : [-210.998, 211.012, 37.890]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-210.998, 211.012, 37.890]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-210.998, 211.012, 37.890, -210.998, 211.012, 37.890, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-170.992, 208.924, 25.000]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-170.992, 208.924, 25.000]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-170.992, 208.924, 25.000, -170.992, 208.924, 25.000, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-171.438, 207.658, 38.810]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-171.438, 207.658, 38.810]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-171.438, 207.658, 38.810, -171.438, 207.658, 38.810, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-132.623, 206.187, 26.930]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-132.623, 206.187, 26.930]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-132.623, 206.187, 26.930, -132.623, 206.187, 26.930, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-133.096, 204.588, 41.334]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-133.096, 204.588, 41.334]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-133.096, 204.588, 41.334, -133.096, 204.588, 41.334, 150]
    'color' : [0.,1.0,0.,1]
'L6 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L6 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-97.283, 202.670, 27.443]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-97.283, 202.670, 27.443]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-97.283, 202.670, 27.443,-97.283, 202.670, 27.443, 150]
    'color' : [0.,1.0,0.,1]
'L6 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/L6 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-97.783, 201.057, 42.700]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-97.783, 201.057, 42.700]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-97.783, 201.057, 42.700, -97.783, 201.057, 42.700, 150]
    'color' : [0.,1.0,0.,1]
'T10 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-392.410, 224.020, 17.862]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-392.410, 224.020, 17.862]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-392.410, 224.020, 17.862, -392.410, 224.020, 17.862, 150]
    'color' : [0.,1.0,0.,1]
'T10 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-392.763, 223.446, 28.992]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-392.763, 223.446, 28.992]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-392.763, 223.446, 28.992, -392.763, 223.446, 28.992, 150]
    'color' : [0.,1.0,0.,1]
'T11 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-358.348, 220.015, 18.997]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-358.348, 220.015, 18.997]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-358.348, 220.015, 18.997, -358.348, 220.015, 18.997, 150]
    'color' : [0.,1.0,0.,1]
'T11 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-358.704, 219.438, 30.227]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-358.704, 219.438, 30.227]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-358.704, 219.438, 30.227, -358.704, 219.438, 30.227, 150]
    'color' : [0.,1.0,0.,1]
'T12 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-321.332, 218.033, 20.794]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-321.332, 218.033, 20.794]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-321.332, 218.033, 20.794,-321.332, 218.033, 20.794, 150]
    'color' : [0.,1.0,0.,1]
'T12 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-321.714, 217.187, 32.582]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-321.714, 217.187, 32.582]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-321.714, 217.187, 32.582,-321.714, 217.187, 32.582, 150]
    'color' : [0.,1.0,0.,1]
'T13 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/T13 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-321.332, 218.033, 20.794]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-321.332, 218.033, 20.794]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-321.332, 218.033, 20.794,-321.332, 218.033, 20.794, 150]
    'color' : [0.,1.0,0.,1]
'T13 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'Mr Pig 1_1/marker 2 space/T13 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-321.714, 217.187, 32.582]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-321.714, 217.187, 32.582]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-321.714, 217.187, 32.582,-321.714, 217.187, 32.582, 150]
    'color' : [0.,1.0,0.,1]