'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-185.515, -50.617, -203.438]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-175.586, -70.922, -221.139]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-175.586, -70.922, -221.139]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-175.586, -70.922, -221.139, -185.515, -50.617, -203.438, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-179.790, -44.130, -245.257]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-173.612, -70.578, -232.336]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-173.612, -70.578, -232.336]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-173.612, -70.578, -232.336, -179.790, -44.130, -245.257, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-152.474, -39.986, -199.342]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-143.336, -59.138, -215.363]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-143.336, -59.138, -215.363]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-143.336, -59.138, -215.363, -152.474, -39.986, -199.342, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-146.373, -34.159, -239.041]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-141.275, -58.779, -227.053]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-141.275, -58.779, -227.053]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-141.275, -58.779, -227.0531,-146.373, -34.159, -239.041, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-119.148, -23.746, -196.216]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-109.615, -45.943, -209.139]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-109.615, -45.943, -209.1398]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-109.615, -45.943, -209.139,-119.148, -23.746, -196.216, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-115.766, -17.394, -223.281]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-107.207, -45.397, -220.908]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-107.207, -45.397, -220.908]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-107.207, -45.397, -220.908, -115.766, -17.394, -223.281, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-85.999, -5.672, -198.022]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-76.914, -31.789, -200.017]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-76.914, -31.789, -200.017]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-76.914, -31.789, -200.017,-85.999, -5.672, -198.022, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-74.508, -15.411, -233.022]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-74.130, -31.333, -212.682]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-74.130, -31.333, -212.682]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-74.130, -31.333, -212.682,-74.508, -15.411, -233.022, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-51.218, -5.109, -175.773]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-43.031, -18.536, -191.964]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-43.031, -18.536, -191.964]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-43.031, -18.536, -191.964,-51.218, -5.109, -175.773, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-43.071, 0.489, -220.108]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-40.128, -18.416, -205.429]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-40.128, -18.416, -205.429]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-40.128, -18.416, -205.429, -43.071, 0.489, -220.108, 150]
    'color' : [0.,1.0,0.,1]
'L6 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L6 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-20.215, 11.640, -172.568]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-9.678, -4.955, -186.060]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-9.678, -4.955, -186.060]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-9.678, -4.955, -186.060,-20.215, 11.640, -172.568, 150]
    'color' : [0.,1.0,0.,1]
'L6 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/L6 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-17.401, 15.523, -204.486]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-7.370, -4.687, -200.651]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-7.370, -4.687, -200.651]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-7.370, -4.687, -200.651, -17.401, 15.523, -204.486, 150]
    'color' : [0.,1.0,0.,1]
'T13 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/T13 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-279.945, -83.128, -222.169]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-271.093, -97.078, -237.675]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-271.093, -97.078, -237.675]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-271.093, -97.078, -237.675,-279.945, -83.128, -222.169, 150]
    'color' : [0.,1.0,0.,1]
'T13 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/T13 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-274.180, -79.687, -260.864]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-269.201, -97.218, -247.468]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-269.201, -97.218, -247.468]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-269.201, -97.218, -247.468,-274.180, -79.687, -260.864, 150]
    'color' : [0.,1.0,0.,1]
'T14 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/T14 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-251.386, -71.813, -222.941]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-242.986, -91.411, -234.054]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-242.986, -91.411, -234.054]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-242.986, -91.411, -234.054,-251.386, -71.813, -222.941, 150]
    'color' : [0.,1.0,0.,1]
'T14 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/T14 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-249.798, -62.904, -246.957]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-241.101, -91.415, -244.180]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-241.101, -91.415, -244.1802]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-241.101, -91.415, -244.180,-249.798, -62.904, -246.957, 150]
    'color' : [0.,1.0,0.,1]
'T15 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/T13 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-219.390, -52.451, -226.974]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-210.414, -79.440, -228.284]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-210.414, -79.440, -228.284]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-210.414, -79.440, -228.284,-219.390, -52.451, -226.974, 150]
    'color' : [0.,1.0,0.,1]
'T15 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'MISTER_PIG 4-stls/marker2/T13 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-210.516, -64.647, -253.059]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-208.491, -79.279, -238.885]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-208.491, -79.279, -238.885]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-208.491, -79.279, -238.885,-210.516, -64.647, -253.059, 150]
    'color' : [0.,1.0,0.,1]