'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-262.015, 96.534, 5.446]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-264.410, 135.170, 18.806]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-264.410, 135.170, 18.806]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [ -264.410, 135.170, 18.806,-262.015, 96.534, 5.446, 100]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-258.466, 90.684, 44.082]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-262.928, 134.740, 38.496]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-262.928, 134.740, 38.496]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-262.928, 134.740, 38.496,-258.466, 90.684, 44.0827, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-229.193, 101.976, 6.686]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-233.653, 141.712, 15.486]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-233.653, 141.712, 15.486]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [ -233.653, 141.712, 15.486,-229.193, 101.976, 6.686, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-226.767, 106.153, 35.000]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-231.311, 140.644, 37.889]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-231.311, 140.644, 37.889]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-231.311, 140.644, 37.889,-226.767, 106.153, 35.000, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-201.670, 109.825, 8.792]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-200.395, 150.079, 19.711]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-200.395, 150.079, 19.711]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-200.395, 150.079, 19.711,-201.670, 109.825, 8.792, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-196.678, 109.961, 48.508]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-198.792, 149.128, 31.363]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-198.792, 149.128, 31.363]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-198.792, 149.128, 31.363,-196.678, 109.961, 48.508, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-174.246, 110.359, -11.913]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-167.581, 145.527, 10.722]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-167.581, 145.527, 10.722]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-167.581, 145.527, 10.722,-174.246, 110.359, -11.913,  150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-164.932, 99.258, 44.289]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-165.084, 145.359, 24.852]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-165.084, 145.359, 24.852]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-165.084, 145.359, 24.852,-164.932, 99.258, 44.289, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-147.835, 110.986, -14.490]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-136.010, 141.229, 5.947]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-136.010, 141.229, 5.947]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-136.010, 141.229, 5.947,-147.835, 110.986, -14.490, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-144.057, 105.943, 30.200]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-134.182, 141.082, 21.591]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-134.182, 141.082, 21.591]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-134.182, 141.082, 21.591,-144.057, 105.943, 30.200,  150]
    'color' : [0.,1.0,0.,1]
'T10 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-339.504, 89.248, 57.119]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-342.817, 126.501, 52.875]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-342.817, 126.501, 52.875]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-342.817, 126.501, 52.875,-339.504, 89.248, 57.119,  150]
    'color' : [0.,1.0,0.,1]
'T10 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-348.503, 79.137, 23.176]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-346.624, 126.577, 39.377]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-346.624, 126.577, 39.377]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-346.624, 126.577, 39.377,-348.503, 79.137, 23.176, 150]
    'color' : [0.,1.0,0.,1]
'T11 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-318.550, 84.336, 18.410]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-318.489, 124.968, 33.196]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-318.489, 124.968, 33.196]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-318.489, 124.968, 33.196,-318.550, 84.336, 18.410,  150]
    'color' : [0.,1.0,0.,1]
'T11 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'S210404-stls/marker1/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-312.560, 88.469, 46.359]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-315.746, 124.533, 45.281]
    'color' : [1.0,1.0,1.0,.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-315.746, 124.533, 45.281]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-315.746, 124.533, 45.281,-312.560, 88.469, 46.359,  150]
    'color' : [0.,1.0,0.,1]