'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-48.281, 213.249, -9.889]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-62.339, 222.215, -24.311]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-80.310, 233.675, -42.747]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-80.310, 233.675, -42.747, -62.339, 222.215, -24.311, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-32.301, 216.581, -52.298]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-51.510, 224.342, -51.960]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-76.228, 234.330, -51.526]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-76.228, 234.330, -51.526, -51.510, 224.342, -51.960, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-61.016, 182.985, -15.797]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-72.398, 188.443, -27.338]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-94.320, 198.954, -49.566]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-94.320, 198.954, -49.566, -72.398, 188.443, -27.338, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-42.597, 182.785, -57.410]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-58.842, 188.312, -57.410]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-91.007, 199.255, -57.410]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-91.007, 199.255, -57.410, -58.842, 188.312, -57.410, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-74.167, 149.988, -21.388]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-83.691, 154.211, -32.110]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-104.102, 163.260, -55.088]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-104.102, 163.260, -55.088, -83.691, 154.211, -32.110, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-55.876, 149.137, -63.342]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-69.237, 152.984, -63.110]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-101.077, 162.152, -62.555]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-101.077, 162.152, -62.555, -69.237, 152.984, -63.110, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-81.706, 112.521, -22.659]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-91.485, 114.359, -33.699]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-113.654, 118.527, -58.726]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-113.654, 118.527, -58.726, -91.485, 114.359, -33.699, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-62.077, 111.203, -67.664]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-76.568, 113.203, -68.013]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-109.796, 117.789, -68.812]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-109.796, 117.789, -68.812, -76.568, 113.203, -68.013, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-87.816, 78.296, -17.374]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-96.283, 76.155, -31.494]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-111.276, 72.363, -56.495]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-111.276, 72.363, -56.495, -96.283, 76.155, -31.494, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-10/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-63.803, 78.969, -74.328]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-78.828, 76.697, -71.720]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-105.843, 72.613, -67.032]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-105.843, 72.613, -67.032, -78.828, 76.697, -71.720, 150]
    'color' : [0.,1.0,0.,1]