'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-66.093, 212.446, -7.071]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-77.662, 218.830, -17.185]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-101.173, 231.804, -37.738]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-101.173, 231.804, -37.738, -77.662, 218.830, -17.185, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-53.192, 216.304, -49.792]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-66.464, 221.170, -48.661]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-98.178, 232.798, -45.958]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-98.178, 232.798, -45.958, -66.464, 221.170, -48.661, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-76.922, 182.513, -12.386]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-89.045, 187.290, -23.336]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-113.004, 196.730, -44.980]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-113.004, 196.730, -44.980, -89.045, 187.290, -23.336, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-60.067, 184.994, -55.772]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-76.608, 189.241, -55.118]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-109.033, 197.568, -53.836]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-109.033, 197.568, -53.836, -76.608, 189.241, -55.118, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-87.053, 148.164, -17.842]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-97.724, 151.355, -27.935]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-119.993, 158.013, -48.997]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-119.993, 158.013, -48.997, -97.724, 151.355, -27.935, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-71.134, 149.481, -60.479]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-84.935, 151.673, -59.961]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-117.641, 156.865, -58.732]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-117.641, 156.865, -58.732, -84.935, 151.673, -59.961, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-91.657, 111.322, -19.371]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-102.115, 111.871, -29.659]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-126.117, 113.133, -53.271]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-126.117, 113.133, -53.271, -102.115, 111.871, -29.659, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-74.644, 110.715, -65.399]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-89.266, 111.019, -64.853]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-122.787, 111.716, -63.603]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-122.787, 111.716, -63.603, -89.266, 111.019, -64.853, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-93.980, 76.845, -13.818]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-104.005, 73.765, -27.239]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-120.151, 68.805, -48.854]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-120.151, 68.805, -48.854, -104.005, 73.765, -27.239, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-11/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-74.156, 79.513, -72.522]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-88.691, 76.032, -69.126]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-114.980, 69.736, -62.984]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-114.980, 69.736, -62.984, -88.691, 76.032, -69.126, 150]
    'color' : [0.,1.0,0.,1]