'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-53.300, 214.674, -17.659]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-64.617, 220.252, -28.847]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-87.313, 231.436, -51.282]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-87.313, 231.436, -51.282, -64.617, 220.252, -28.847, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-38.731, 216.247, -59.722]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-52.090, 220.840, -59.658]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-84.134, 231.858, -59.503]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-84.134, 231.858, -59.503, -52.090, 220.840, -59.658, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-65.208, 183.447, -21.760]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-76.671, 188.255, -33.931]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-98.376, 197.358, -56.978]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-98.376, 197.358, -56.978, -76.671, 188.255, -33.931, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-46.760, 181.551, -63.344]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-63.205, 186.677, -64.336]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-94.984, 196.583, -66.253]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-94.984, 196.583, -66.253, -63.205, 186.677, -64.336, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-78.634, 151.232, -26.664]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-88.124, 154.364, -37.420]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-110.360, 161.703, -62.623]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-110.360, 161.703, -62.623, -88.124, 154.364, -37.420, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-59.715, 149.096, -67.619]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-73.113, 152.110, -68.225]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-107.353, 159.813, -69.774]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-107.353, 159.813, -69.774, -73.113, 152.110, -68.225, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-85.305, 114.845, -26.387]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-94.954, 115.370, -37.483]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-117.050, 116.573, -62.891]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-117.050, 116.573, -62.891, -94.954, 115.370, -37.483, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-65.236, 110.970, -70.931]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-79.612, 112.015, -71.510]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-111.934, 114.366, -72.813]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-113.659, 117.223, -69.795, -79.612, 112.015, -71.510, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-90.093, 79.695, -19.415]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-99.037, 76.072, -32.996]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-113.763, 70.107, -55.358]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-113.763, 70.107, -55.358, -99.037, 76.072, -32.996, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-7/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-66.181, 77.672, -76.183]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-80.700, 74.942, -73.698]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-107.567, 69.891, -69.099]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-107.567, 69.891, -69.099, -80.700, 74.942, -73.698, 150]
    'color' : [0.,1.0,0.,1]