'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-49.774, 215.554, -8.197]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-61.417, 221.675, -18.117]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-85.314, 234.238, -38.479]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-85.314, 234.238, -38.479, -61.417, 221.675, -18.117, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-33.634, 218.929, -46.621]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-47.583, 223.729, -47.585]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-79.556, 234.733, -49.795]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-79.556, 234.733, -49.795, -47.583, 223.729, -47.585, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-63.316, 184.103, -12.328]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-74.244, 189.921, -24.584]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-94.907, 200.923, -47.759]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-94.907, 200.923, -47.759, -74.244, 189.921, -24.584, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-43.147, 184.628, -53.454]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-59.989, 190.484, -54.324]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-91.594, 201.475, -55.958]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-91.594, 201.475, -55.958, -59.989, 190.484, -54.324, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-76.484, 151.388, -20.058]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-85.965, 155.098, -30.889]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-105.970, 162.926, -53.743]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-105.970, 162.926, -53.743, -85.965, 155.098, -30.889, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-57.274, 150.978, -60.856]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-70.815, 154.298, -61.458]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-102.970, 162.179, -62.886]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-102.970, 162.179, -62.886, -70.815, 154.298, -61.458, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-83.825, 113.211, -22.597]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-93.443, 115.145, -34.031]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-115.913, 119.662, -60.745]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-115.913, 119.662, -60.745, -93.443, 115.145, -34.031, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-62.954, 113.608, -67.001]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-77.586, 115.208, -67.753]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-110.896, 118.853, -69.464]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-110.896, 118.853, -69.464, -77.586, 115.208, -67.753, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-88.504, 79.861, -18.406]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-97.520, 77.931, -32.406]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-114.155, 74.369, -58.238]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-114.155, 74.369, -58.238, -97.520, 77.931, -32.406, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-12/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-64.592, 80.391, -74.615]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-79.064, 78.443, -72.527]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-110.050, 74.273, -68.057]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-110.050, 74.273, -68.057, -79.064, 78.443, -72.527, 150]
    'color' : [0.,1.0,0.,1]