'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-51.974, 213.087, -12.363]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-62.762, 219.372, -23.919]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-84.205, 231.865, -46.890]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-84.205, 231.865, -46.890, -62.762, 219.372, -23.919, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-35.747, 214.342, -54.336]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-49.114, 219.709, -54.501]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-80.558, 232.333, -54.890]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-80.558, 232.333, -54.890, -49.114, 219.709, -54.501, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-64.138, 182.594, -17.702]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-74.728, 187.491, -29.890]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-96.174, 197.409, -54.572]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-96.174, 197.409, -54.572, -74.728, 187.491, -29.890, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-44.600, 181.530, -59.013]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-60.827, 186.703, -59.688]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-92.721, 196.869, -61.016]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-92.721, 196.869, -61.016, -60.827, 186.703, -59.688, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-75.688, 148.212, -23.043]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-85.407, 152.003, -34.205]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-106.475, 160.220, -58.403]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-106.475, 160.220, -58.403, -85.407, 152.003, -34.205, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-56.835, 147.052, -64.104]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-70.534, 150.470, -64.746]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-102.653, 158.484, -66.253]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-102.653, 158.484, -66.253, -70.534, 150.470, -64.746, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-84.530, 111.907, -23.929]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-94.191, 113.061, -35.357]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-115.734, 115.635, -60.841]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-115.734, 115.635, -60.841, -94.191, 113.061, -35.357, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-63.467, 109.625, -69.614]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-78.067, 111.011, -69.747]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-111.468, 114.181, -70.051]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-111.468, 114.181, -70.051, -78.067, 111.011, -69.747, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-87.484, 78.808, -18.457]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-97.041, 75.327, -32.639]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-112.062, 69.854, -54.930]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-112.062, 69.854, -54.930, -97.041, 75.327, -32.639, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-9/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-65.625, 77.298, -75.526]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-80.045, 74.605, -72.933]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-106.879, 69.593, -68.108]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-106.879, 69.593, -68.108, -80.045, 74.605, -72.933, 150]
    'color' : [0.,1.0,0.,1]