'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-58.025, 214.784, -14.702]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-69.240, 219.526, -26.814]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-91.323, 228.863, -50.662]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-91.323, 228.863, -50.662, -69.240, 219.526, -26.814, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L1 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-41.617, 217.044, -55.935]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-55.315, 220.783, -56.578]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-87.971, 229.697, -58.111]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-87.971, 229.697, -58.111, -55.315, 220.783, -56.578, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-68.722, 180.314, -19.430]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-79.944, 185.169, -32.069]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-101.673, 194.569, -56.541]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-101.673, 194.569, -56.541, -79.944, 185.169, -32.069, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L2 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-47.804, 180.513, -59.212]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-65.091, 185.453, -60.883]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-97.534, 194.723, -64.018]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-97.534, 194.723, -64.018, -65.091, 185.453, -60.883, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-80.356, 148.295, -25.263]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-90.039, 151.572, -36.499]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-111.318, 158.773, -61.189]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-111.318, 158.773, -61.189, -90.039, 151.572, -36.499, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L3 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-60.883, 147.734, -65.342]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-74.857, 150.437, -66.178]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-108.554, 156.952, -68.195]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-108.554, 156.952, -68.195, -74.857, 150.437, -66.178, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-87.817, 112.257, -26.400]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-97.406, 112.714, -37.533]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-119.384, 113.759, -63.049]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-119.384, 113.759, -63.049, -97.406, 112.714, -37.533, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L4 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-66.865, 110.744, -70.867]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-81.730, 111.174, -71.538]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-115.234, 112.144, -73.050]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-115.234, 112.144, -73.050, -81.730, 111.174, -71.538, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-91.964, 78.374, -19.915]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-100.887, 74.667, -34.151]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-115.113, 68.757, -56.849]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-115.113, 68.757, -56.849, -100.887, 74.667, -34.151, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'W926-13/L5 (GC 1.5 SD 0.5).stl'
  'entry':
    'type' : 'point'
    'data' : [-67.073, 78.040, -76.840]
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-81.916, 74.806, -74.577]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-108.706, 68.970, -70.494]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-108.706, 68.970, -70.494, -81.916, 74.806, -74.577, 150]
    'color' : [0.,1.0,0.,1]