'L1 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-288.124, 211.668, 1.564]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-288.124, 211.668, 1.564]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-288.124, 211.668, 1.564, -288.124, 211.668, 1.564, 150]
    'color' : [0.,1.0,0.,1]
'L1 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L1 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-288.482, 210.273, 14.056]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-288.482, 210.273, 14.056]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-288.482, 210.273, 14.056, -288.482, 210.273, 14.056, 150]
    'color' : [0.,1.0,0.,1]
'L2 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-250.749, 210.868, 2.760]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-250.749, 210.868, 2.760]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-250.749, 210.868, 2.760,-250.749, 210.868, 2.760, 150]
    'color' : [0.,1.0,0.,1]
'L2 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L2 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-251.117, 209.437, 15.575]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-251.117, 209.437, 15.575]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-251.117, 209.437, 15.575,-251.117, 209.437, 15.575, 150]
    'color' : [0.,1.0,0.,1]
'L3 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-213.573, 208.917, 3.960]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-213.573, 208.917, 3.960]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-213.573, 208.917, 3.960, -213.573, 208.917, 3.960, 150]
    'color' : [0.,1.0,0.,1]
'L3 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L3 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-213.957, 207.422, 17.346]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-213.957, 207.422, 17.346]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-213.957, 207.422, 17.346, -213.957, 207.422, 17.346, 150]
    'color' : [0.,1.0,0.,1]
'L4 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-173.957, 206.139, 4.333]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-173.957, 206.139, 4.333]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-173.957, 206.139, 4.333, -173.957, 206.139, 4.333, 150]
    'color' : [0.,1.0,0.,1]
'L4 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L4 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-174.353, 204.599, 18.117]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-174.353, 204.599, 18.117]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-174.353, 204.599, 18.117, -174.353, 204.599, 18.117, 150]
    'color' : [0.,1.0,0.,1]
'L5 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-135.549, 203.897, 6.128]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-135.549, 203.897, 6.128]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-135.549, 203.897, 6.128, -135.549, 203.897, 6.128, 150]
    'color' : [0.,1.0,0.,1]
'L5 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L5 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-135.966, 202.012, 20.500]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-135.966, 202.012, 20.500]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-135.966, 202.012, 20.500, -135.966, 202.012, 20.500, 150]
    'color' : [0.,1.0,0.,1]
'L6 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L6 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-100.163, 200.862, 6.498]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-100.163, 200.862, 6.498]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-100.163, 200.862, 6.498, -100.163, 200.862, 6.498, 150]
    'color' : [0.,1.0,0.,1]
'L6 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/L6 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-100.604, 198.945, 21.722]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-100.604, 198.945, 21.722]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-100.604, 198.945, 21.722, -100.604, 198.945, 21.722, 150]
    'color' : [0.,1.0,0.,1]
'T10 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-395.579, 218.301, -2.041]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-395.579, 218.301, -2.041]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-395.579, 218.301, -2.041, -395.579, 218.301, -2.041, 150]
    'color' : [0.,1.0,0.,1]
'T10 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/T10 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-395.897, 217.506, 9.076]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-395.897, 217.506, 9.076]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-395.897, 217.506, 9.076,-395.897, 217.506, 9.076, 150]
    'color' : [0.,1.0,0.,1]
'T11 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-361.462, 214.747, -1.056]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-361.462, 214.747, -1.056]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-361.462, 214.747, -1.056, -361.462, 214.747, -1.056, 150]
    'color' : [0.,1.0,0.,1]
'T11 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/T11 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-361.783, 213.947, 10.161]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-361.783, 213.947, 10.161]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-361.783, 213.947, 10.161, -361.783, 213.947, 10.161, 150]
    'color' : [0.,1.0,0.,1]
'T12 - left':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-324.418, 213.243, 0.623]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-324.418, 213.243, 0.623]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-324.418, 213.243, 0.623, -324.418, 213.243, 0.623, 150]
    'color' : [0.,1.0,0.,1]
'T12 - right':
  'L':
    'focus' : true
    'type' : 'mesh'
    'data' : 'right marker/T12 (GC 3 SD 1.5).stl'
  'entry':
    'type' : 'point'
    'data' : []
    'color' : [0.,1.,0.0,1.0]
  'mid':
    'type' : 'point'
    'data' : [-324.760, 212.164, 12.394]
    'color' : [1.0,1.0,1.0,0.5]
  'screw-tip':
    'type' : 'point'
    'data' : [-324.760, 212.164, 12.394]
    'color' : [1.0,1.0,1.0,.5]
  'traj':
    'type' : 'line'
    'data' : [-324.760, 212.164, 12.394, -324.760, 212.164, 12.394, 150]
    'color' : [0.,1.0,0.,1]